/**
 * Game constants and configuration values.
 * Centralizes magic numbers for easier maintenance and tuning.
 */

export const COMBAT_CONSTANTS = {
  MAX_MANA: 100,
  MANA_REGEN_INTERVAL: 250,
  STATUS_EFFECTS_INTERVAL: 1000,
  ENHANCED_REGEN_INTERVAL: 1000,
  HP_LOSS_INTERVAL: 1000,
  DRUMS_INTERVAL: 1000,
  FROST_NOVA_INTERVAL: 1000,
  SHIELD_LOSS_INTERVAL: 1800,
  BATTLE_END_DELAY: 3000
};

export const TIMER_CONSTANTS = {
  ROUND_DURATION: 50,
  BUFFER_DURATION: 30,
  DAMAGE_ESCALATION_START: 20,
  DAMAGE_ESCALATION_RATE: 0.06,
  SELECTION_DURATION: 50
};

export const PLAYER_CONSTANTS = {
  MAX_HEALTH: 50,
  STARTING_GOLD: 300,
  BASE_HEALTH_LOSS: 2,
  MAX_CONSECUTIVE_LOSS_BONUS: 3
};

export const SHOP_CONSTANTS = {
  ITEM_TIER_1_COST: 100,
  ITEM_TIER_2_COST: 200,
  ITEM_TIER_3_COST: 300,
  BASE_REROLL_COST: 50
};

export const ROUND_CONSTANTS = {
  MINION_ROUNDS: [5, 10, 15, 20],
  ARTIFACT_ROUNDS: [3, 8, 13]
};

export const ECONOMY_CONSTANTS = {
  BASE_WIN_REWARD: 250,
  BASE_ROUND_REWARD: 50,
  WIN_STREAK_BONUS: 25,
  MAX_WIN_STREAK_BONUS: 150,
  LOSS_STREAK_BONUS: 20,
  MAX_LOSS_STREAK_BONUS: 150,
  HP_LOSS_REWARD_MULTIPLIER: 20
};
